- name: Run ft_transcendence
  hosts: virtualmachines
  become: true
  tasks:
    - name: Uninstall old Docker packages
      ansible.builtin.apt:
        name: docker, docker-engine, docker.io, containerd, runc
        state: absent
    - name: Update sytem and packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
    - name: Install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        name: ca-certificates, curl, gnupg, lsb-release
        state: present
    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Set up the stable repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: Update system and install Docker Engine
      ansible.builtin.apt:
        name: docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin
        state: present
        update_cache: true
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
    - name: Install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
    - name: Install docker python module
      ansible.builtin.pip:
        name: docker, docker_compose
    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present
    - name: Clone ft_transcendence
      ansible.builtin.git:
        repo: https://github.com/kema-dev/ft_transcendence.git
        dest: /home/{{ ansible_user }}/ft_transcendence
    - name: Populate environnement variables
      ansible.builtin.copy:
        content: |
          BACKEND_PORT=3000
          FRONTEND_PORT_HTTP=80
          FRONTEND_PORT_HTTPS=443
          FRONTEND_EXPOSED_HTTP=80
          FRONTEND_EXPOSED_HTTPS=443
          VUE_PHASE=serve
          NEST_PHASE=start:dev
          POSTGRESQL_PASSWORD=postgres_pass
          POSTGRESQL_DATABASE=postgres_db
          POSTGRESQL_PORT=5432
          POSTGRESQL_USERNAME=postgres
          POSTGRESQL_HOST=localhost
          POSTGRESQL_POSTGRES_PASSWORD=postgres_pass
          PGADMIN_PORT_HTTP=80
          PGADMIN_HOST_PORT=8080
          PGADMIN_EMAIL=pgadmin@example.com
          PGADMIN_PASSWORD=pgadmin_pass
          JWT_MAX_AGE=86400
          API_42_UID=38262d46e03eb3f2c3087994e6a92ffe63356d0f7335fc1ed54d671843af34b8
          API_42_SECRET=a8bc9dac0e43e031cf56a69de2604242a9875aef48710dc72eac4f1b02a8deb7
          API_42_REDIRECT_URI=https://localhost/
        dest: /home/{{ ansible_user }}/ft_transcendence/.env
        mode: '600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: Run docker-compose
      ansible.builtin.docker_compose:
        project_src: /home/{{ ansible_user }}/ft_transcendence
        state: present
        build: true
